package br.com.prenatal.entity.enumeration;

public enum GrauEscolaridade {
	ANALFABETO, FUNDAMENTAL_INCOMPLETO, FUNDAMENTAL_COMPLETO, MEDIO_INCOMPLETO, MEDIO_COMPLETO, SUPERIOR_INCOMPLETO, SUPERIOR_COMPLETO, MESTRADO, DOUTORADO;
}
